name: .NET Build & Test
description: "Restore, build, test and publish a .NET project"

inputs:
  dotnet-channel:
    description: ".NET channel to install (e.g. 9.0, 8.0)"
    required: false
    default: "10.0"
  project-path:
    description: "Path to .csproj or solution"
    required: false
    default: "."
  run-tests:
    description: "Whether to run tests"
    required: false
    default: "true"
  publish-output:
    description: "Output folder for dotnet publish"
    required: false
    default: "./publish"

outputs:
  artifact-name:
    description: "Name of the uploaded artifact"
    value: ${{ steps.upload.outputs.artifact-name }}

runs:
  using: composite
  steps:
 #   - name: Install .NET
 #     shell: bash
 #     run: |
 #       curl -fsSL https://dot.net/v1/dotnet-install.sh | bash -s -- --channel ${{ inputs.dotnet-channel }}
 #       echo "$HOME/.dotnet" >> $GITHUB_PATH
 #       echo "DOTNET_ROOT=$HOME/.dotnet" >> $GITHUB_ENV

    - name: Restore
      shell: bash
      run: dotnet restore ${{ inputs.project-path }}

    - name: Build
      shell: bash
      run: dotnet build ${{ inputs.project-path }} --no-restore --configuration Release

    - name: Test
      if: ${{ inputs.run-tests == 'true' }}
      shell: bash
      run: dotnet test ${{ inputs.project-path }} --no-build --configuration Release --logger trx

    - name: Publish
      shell: bash
      run: dotnet publish ${{ inputs.project-path }} --no-build --configuration Release --output ${{ inputs.publish-output }}

    - name: Upload artifact
      id: upload
      uses: actions/upload-artifact@v4
      with:
        name: dotnet-publish
        path: ${{ inputs.publish-output }}
